name: Test All

on:
  push:
    branches: [ "main", "Development" ]
  pull_request:
    branches: [ "main", "Development" ]

jobs:
  test-frontend:
    uses: ./.github/workflows/test_frontend.yml
    secrets: inherit

  test-backend:
    uses: ./.github/workflows/test_backend.yml
    secrets: inherit
